# Site settings
title: DevDrops
email: davi.marcondes.moreira@gmail.com
description: "My personal site."
baseurl: ""
url: "http://www.devdrops.me"
twitter_username: devdrops
github_username:  devdrops

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
