# Site settings
title: DevDrops
email: davi.marcondes.moreira@gmail.com
description: "PHP | JS | CSS | WEB | STUFF"
baseurl: ""
url: "http://www.devdrops.me"
twitter_username: devdrops
github_username:  devdrops

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'CNAME', 'README.md', '.gitignore', '.sass-cache', 'Gemfile.lock']

harmony:
  name: DevDrops
  description: My personal site.
  meta_description: > #
   My personal site.
  basetheme: theme-base-01
  author:
    name: Davi Marcondes Moreira
    email: davi.marcondes.moreira@gmail.com
    url: http://www.devdrops.me
  google_analytics_key:
  social:
    github: devdrops
    twitter: devdrops
    facebook:
    gplus: +DaviMarcondesMoreira
    dribble:
    pinterest:
  show_disclaimer: true

highlighter: pygments
sass:
  sass_dir: assets/css/_sass
  style: :compressed
